---

- name: install kafka
  hosts: "{{ host_list }}"
  gather_facts: False
  roles:
  - role: install_kafka


#ansible-playbook -i hosts install_kafka.yml -e "host_list=192.168.88.1, broker_id=0" -k
#注意事项
#1、执行ansible命令的用户在远程机必须能够免密sudo
#2、执行之前根据实际需求更改role/install_kafka/defaults/main.yml
#3、执行之前根据实际需求更改role/install_kafka/templates/server.properties, 一般无需更改
#4、如host_list=192.168.88.1, broker_id=0 这里的一个节点对应一个id就行
