---

- name: install alertmanager
  hosts: "{{ host_list }}"
  gather_facts: True
  roles:
  - role: install_alertmanager


#ansible-playbook -i hosts install_alertmanager.yml -e "host_list=192.168.88.1" -k
##注意事项
##1、执行ansible命令的用户在远程机必须能够免密sudo
##2、执行之前根据实际需求更改role/install_alertmanager/defaults/main.yml或传参
