- name: generate {{ domain }}.conf
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: yes
  with_items:
    - {"src": "nginx_conf_template", "dest": "{{ nginx_conf_dir }}/{{ domain }}.conf"}
  become: yes
  become_method: sudo
  when: type == "change"


- name: move {{ domain }}.conf
  command: mv {{ nginx_conf_dir }}/{{ domain }}.conf {{ nginx_conf_dir }}/{{ domain }}.conf_$(date +%Y%m%d%H%M%S)_delete
  when: type == "delete"
  become: yes
  become_method: sudo


- name: test nginx file and reload  
  command: /opt/nginx/sbin/nginx -t
  become: yes
  become_method: sudo


- name: reload nginx service
  command: /opt/nginx/sbin/nginx -s reload
  become: yes
  become_method: sudo

