---

- name: download and unarchive blackbox_exporter pkg
  unarchive:
    src: "{{file_server}}/{{ blackbox_exporter_pkg }}"
    dest: "{{ deployment_dir }}"
    remote_src: yes
    owner: "{{ run_user }}"
    group: "{{ run_usergroup }}"
  become: yes
  become_method: sudo


- name: create blackbox_exporter soft link
  file:
    src: "{{ deployment_dir }}/{{ blackbox_exporter_version }}"
    dest: "{{ deployment_dir }}/blackbox_exporter"
    state: link
    owner: "{{ run_user }}"
    group: "{{ run_usergroup }}"
  become: yes
  become_method: sudo


- name: make sure blackbox_exporter  log directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ run_user }}"
    group: "{{ run_usergroup }}"
    mode: 0755
  with_items:
    - "{{ blackbox_exporter_log_dir }}"
  become: yes
  become_method: sudo


- name: generate init.blackbox_exporter.sh
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
    owner: "{{ run_user }}"
    group: "{{ run_usergroup }}"
  with_items:
    - {"src": "init.blackbox_exporter.sh", "dest": "{{ deployment_dir }}/blackbox_exporter/init.blackbox_exporter.sh"}
  become: yes
  become_method: sudo
