---

- name: download and unarchive pkg
  unarchive:
    src: "{{file_server}}/{{ pkg }}"
    dest: "{{ deployment_dir }}"
    remote_src: yes
    owner: "{{ run_user }}"
    group: "{{ run_usergroup }}"
  become: yes
  become_method: sudo


- name: create soft link
  file:
    src: "{{ deployment_dir }}/{{ pkg_version }}"
    dest: "{{ deployment_dir }}/blackbox_exporter"
    state: link
    owner: "{{ run_user }}"
    group: "{{ run_usergroup }}"
  become: yes
  become_method: sudo


- name: make sure log directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ run_user }}"
    group: "{{ run_usergroup }}"
    mode: 0755
  with_items:
    - "{{ log_dir }}"
  become: yes
  become_method: sudo


- name: generate service script
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
    owner: "{{ run_user }}"
    group: "{{ run_usergroup }}"
  with_items:
    - {"src": "init.blackbox_exporter.sh", "dest": "{{ deployment_dir }}/blackbox_exporter/init.blackbox_exporter.sh"}
  become: yes
  become_method: sudo
